### ISSUE TITLE
Airline or Lightline support?

### ISSUE THREAD

**Issue by cultab** [romgrk/github-light.vim#1]
In the screenshots there appears to be an airline theme that exists? Is it external or is it a part of this colorscheme that is not yet included?

**Comment by romgrk** [comment]
There isn't statusline support :/

The colorscheme defines highlights for `StatusLine` and `StatusLineNC` but that's it. The highlighting comes from my [custom statusline](https://github.com/romgrk/nvim/blob/master/plugin/statusline.vim) (forked it from somewhere). I didn't have a statusline until very recently so I did all that theming manually.

I don't have enough motivation to fine-tune the colorscheme for other statusline plugins, but what I could do would be to expose the highlight groups I use in my statusline in the theme, those could then be `highlight! link`ed to airline/lightline groups.

eg
```vim
hi! link AirlineNormal StatuslineNormal
hi! link AirlineInsert StatuslineInsert
" ...
```

Which of those plugins do you use? If you can find me the highlight groups that must be defined I could include those in the colorscheme.

**Comment by cultab** [comment]
I use lightline so I don't know about airline but it seems [lightline does not use highlight groups for it's colors](https://github.com/itchyny/lightline.vim/blob/c172131e0369672bc1b9454a2aec6d532d350dcc/doc/lightline.txt#L552).

I could take a look at really basic support within the week and pull request it.

**Comment by cultab** [comment]
Created the pull request here: #2
