### ISSUE TITLE
Cursor is missing in nvim terminal

### ISSUE THREAD

**Issue by lourenci** [romgrk/github-light.vim#6]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/2339362/118813892-faa1c900-b885-11eb-955e-f327cd66449f.png">

Thanks for the colorscheme.

**Comment by romgrk** [comment]
What's your output for `hi TermCursor` and `hi TermCursorNC`? What would be a good highlight for the cursor? I'm on the dark side these days so I'm not using this colorscheme, if you can suggest something it would be great.

**Comment by lourenci** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/2339362/118851445-233aba80-b8a8-11eb-8d72-ee3342374b2a.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/2339362/118851469-2cc42280-b8a8-11eb-9fac-503345691af5.png">

> What would be a good highlight for the cursor?

The same as the normal mode is ok.

> I'm on the dark side these days so I'm not using this colorscheme

Oh, man, I'm very sorry for that.

**Comment by romgrk** [comment]
Are you doing custom mods to your HL groups?

The terminal has a black background in github-light, that's why the cursor is white.

![Screenshot from 2021-05-19 14-35-16](https://user-images.githubusercontent.com/1423607/118865895-72d0b480-b8af-11eb-822f-3b288ed7d5e7.png)

**Comment by huytd** [comment]
I ran into the same issue, turned out it's because I'm using iTerm, which has an option to force the cursor color and it's set to white. It can be changed to other color in Profile setting.
![image](https://user-images.githubusercontent.com/613943/130668076-f0bb661f-f970-4d19-8145-9ee02b0b64be.png)
